#!/bin/bash

# Works with tmux 2.6 on Ubuntu 18.04. Your mileage may vary.
# 'send-keys' exists only to show/prove what's going where: the space prevents command history retention
#   and the hashtag indicates a comment so bash doesn't try to run it.

path=$(pwd)

# Removed: seems unnecessary.
# tmux start-server

# Create new session, and extra windows.
tmux new-session -d

# Split window into two, horizontally: 67%/33% of current window.
tmux split-window -h -l 66%
tmux split-window -h -l 50%

tmux select-pane -t 0
tmux send-keys "cd $path"
tmux send-keys KPEnter
tmux send-keys "reset"
tmux send-keys KPEnter

tmux select-pane -t 1
tmux send-keys "cd $path"
tmux send-keys KPEnter
tmux send-keys "reset"
tmux send-keys KPEnter

tmux select-pane -t 2
tmux send-keys "cd $path"
tmux send-keys KPEnter
tmux send-keys "reset"
tmux send-keys KPEnter

tmux select-pane -t 0

# Make it so. This must be the very last command.
tmux attach-session
