#      ___           ___           ___           ___           ___
#     /  /\         /  /\         /__/\         /  /\         /  /\
#    /  /::|       /  /:/_        \  \:\       /  /::\       /  /:/
#   /  /:/:|      /  /:/ /\        \__\:\     /  /:/\:\     /  /:/
#  /  /:/|:|__   /  /:/ /::\   ___ /  /::\   /  /:/~/:/    /  /:/  ___
# /__/:/ |:| /\ /__/:/ /:/\:\ /__/\  /:/\:\ /__/:/ /:/___ /__/:/  /  /\
# \__\/  |:|/:/ \  \:\/:/~/:/ \  \:\/:/__\/ \  \:\/:::::/ \  \:\ /  /:/
#     |  |:/:/   \  \::/ /:/   \  \::/       \  \::/~~~~   \  \:\  /:/
#     |  |::/     \__\/ /:/     \  \:\        \  \:\        \  \:\/:/
#     |  |:/        /__/:/       \  \:\        \  \:\        \  \::/
#     |__|/         \__\/         \__\/         \__\/         \__\/

# Homebrew
if [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
	export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
	eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

# add local bin before source files
export PATH="/home/heynemann/.local/bin:$PATH"

unsetopt WARN_CREATE_GLOBAL

source ~/.fzf.zsh

unsetopt WARN_CREATE_GLOBAL

source ~/.zsh/general.zsh

unsetopt WARN_CREATE_GLOBAL

source ~/.zsh/bundles.zsh

unsetopt WARN_CREATE_GLOBAL

source ~/.zsh/starship.zsh

unsetopt WARN_CREATE_GLOBAL

source ~/.zsh/go.zsh
source ~/.zsh/node.zsh
source ~/.zsh/cursor.zsh

if [ -f "$HOME/.alias.zsh" ]; then
	source $HOME/.alias.zsh
fi

if [ -f "$HOME/.local.zsh" ]; then
	source $HOME/.local.zsh
fi

unsetopt WARN_CREATE_GLOBAL

# Ensure local bin comes first
export PATH="$(pipx environment --value PIPX_BIN_DIR):$PATH"
export PATH="~/.bin:$PATH"
export PATH="~/.local/bin:$PATH"
export PATH="~/.local/state/fnm_multishells/39814_1759981795493/bin:$PATH"
